repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.(ai|gz)$
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        args: ['--target-version', 'py36']
  - repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.4
    hooks:
      - id: autopep8
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        additional_dependencies: ['hacking']
  - repo: https://github.com/lorenzwalthert/precommit
    rev: v0.1.3
    hooks:
    - id: parsable-R
    - id: style-files
    - id: roxygenize
    - id: no-browser-statement
    - id: deps-in-desc
    - id: use-tidy-description
    - id: codemeta-description-updated
    - id: readme-rmd-rendered
    - id: lintr
      args: [--warn_only]
      verbose: true

